name: Continuous Integration

on:
    pull_request:
      branches:
        - main

env:
    MYSQL_DATABASE: test_user
    DB_USER: root
    RESTORE: .test.sql
    DB_PASSWORD: 123

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        container port: 3306
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql version: '8.0'
        mysql database: ${{ env.MYSQL_DATABASE }}
        mysql root password: ${{ env.DB_PASSWORD }}
        mysql user: ${{ env.DB_USER }}
        mysql password: ${{ env.DB_PASSWORD }}
