name: Continuous Integration

on:
    pull_request:
      branches:
        - main

env:
    MYSQL_DATABASE: test_user
    DB_USER: root
    RESTORE: .test.sql
    DB_PASSWORD: 123

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Initialize MySQL
          run: sudo systemctl start mysql.service
  
        - name: Debug DB_PASSWORD
          run: |
            echo "$DB_PASSWORD"
        
        - name: Initialize first database
          run: |
            mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' \
            -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
  
        - name: Boost user
          run: |
            mysql -e "ALTER USER '${{ env.DB_USER }}'@'localhost' \
            IDENTIFIED WITH mysql_native_password BY 'root';" \
            -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
  
        - name: Check out repository code
          uses: actions/checkout@v3
  
        - name: Install yarn
          run: yarn install --frozen-lockfile
  
        - name: run database tests
          working-directory: ./tests
          run: |
           MYSQL_RESTORE_SOURCE=$RESTORE \
           MYSQL_USERNAME=$DB_USER \
           MYSQL_PASSWORD=$DB_PASSWORD \
           MYSQL_ACTIVE_DATABASE=$MYSQL_DATABASE \
           yarn setup.js

        - name: Run API tests
          working-directory: ./tests  # Adjust the path to your API tests
          run: |
            # Add commands here to run your API tests, for example:
            yarn healthz.test.js
