name: CI
on: push
env:
    MYSQL_DATABASE: test_user
    DB_USER: root
    RESTORE: .test.sql
    DB_PASSWORD: 123

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.1"
          root-password: "${{ env.DB_PASSWORD }}"
          password: "${{ env.DB_PASSWORD }}"

      - run: mysql -u'${{ env.DB_USER }}' -p'${{ env.DB_PASSWORD }}' -e 'SELECT version()'

      - run: |
             mysql -u'${{ env.DB_USER }}' -p'${{ env.DB_PASSWORD }}' -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' \
             -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Boost user
        run: |
             mysql -u'${{ env.DB_USER }}' -p'${{ env.DB_PASSWORD }}' -e "ALTER USER '${{ env.DB_USER }}'@'localhost' \
             IDENTIFIED WITH mysql_native_password BY 'root';"

      - run: mysql -uroot -e 'show databases;'

      - run: mysql -uroot -e 'select user from mysql.user;'

