name: CI

on:
    pull_request:
      branches:
        - main
    workflow_dispatch:

env:
    MYSQL_DATABASE: test_user
    DB_USER: root
    RESTORE: .test.sql
    DB_PASSWORD: 123

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.1"

      - run: mysql -uroot -e 'SELECT version()'

      - run: |
            mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' \
            -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Boost user
        run: |
          mysql -e "ALTER USER '${{ env.DB_USER }}'@'localhost' \
          IDENTIFIED WITH mysql_native_password BY 'root';" \
          -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - run: mysql -uroot -e 'show databases;'
